pub mod blind_play;
pub mod clue_burn;
pub mod critical_save;
pub mod delayed_play_clue;
pub mod direct_play_clue;
pub mod discard_chop;
pub mod discard_known_trash;
pub mod five_save;
pub mod low_level_stall;
pub mod play_clue;
pub mod play_known_playable;
pub mod simple_finesse;
pub mod simple_prompt;
mod tempo_clue;
pub mod two_save;
